-- llm-job-pipeline — Supabase / Postgres schema
--
-- Two tables only: `company` and `vacancy`. Run this once on a fresh
-- Supabase project (SQL Editor → New query → paste → Run).
--
-- All UUIDs are generated by `gen_random_uuid()` from the pgcrypto
-- extension, which is enabled by default on Supabase.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- company — sole source of truth for organisations we monitor.
-- One row per canonical company name. Multiple display names map to the same
-- row through the `aliases` array (used by resolve_canonical_name).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS company (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    canonical_name    TEXT NOT NULL UNIQUE,
    aliases           TEXT[] DEFAULT '{}',

    -- Pipeline gate. Only `active` companies feed the scoring/dashboard.
    -- `candidate` = pending review (found on a job board, not approved yet).
    -- `inactive` = rejected / archived.
    status            TEXT NOT NULL DEFAULT 'candidate'
                      CHECK (status IN ('active', 'candidate', 'inactive')),
    status_reason     TEXT,

    -- Manual or LLM-derived ranking.
    tier              TEXT CHECK (tier IN ('S', 'A', 'B', 'C')),
    category          TEXT,

    -- Official website (filled by scripts/find_company_urls.py /
    -- scripts/fetch_companies.py; used by the enrichment pipeline).
    website           TEXT,

    -- Fetch configuration (see scripts/fetchers.py).
    fetch_strategy    TEXT,         -- e.g. 'greenhouse', 'lever', 'ashby'
    careers_url       TEXT,
    ats_slug          TEXT,
    ats_config        JSONB DEFAULT '{}',

    -- Source tracking, updated by scripts/database_supabase.py.
    last_fetched      TIMESTAMPTZ,
    vacancy_count     INTEGER,
    fetch_status      TEXT,
    fetch_error       TEXT,

    -- Enrichment data (filled by scripts/fetch_companies.py).
    description       TEXT,
    product           TEXT,
    notes             TEXT,
    user_comments     TEXT,
    offices           TEXT,
    experience_match  INTEGER,
    personal_interest INTEGER,
    about             JSONB,
    mission_fit       JSONB,
    alignment_score   INTEGER,
    enriched_at       TIMESTAMPTZ,

    created_at        TIMESTAMPTZ DEFAULT NOW()
);

-- GIN index on aliases — used by resolve_canonical_name and ensure_company.
CREATE INDEX IF NOT EXISTS idx_company_aliases ON company USING GIN (aliases);
CREATE INDEX IF NOT EXISTS idx_company_status  ON company (status);
CREATE INDEX IF NOT EXISTS idx_company_tier    ON company (tier);

-- ---------------------------------------------------------------------------
-- vacancy — one row per job posting. Dedup is enforced by `dedup_hash`,
-- computed as md5(lower(canonical_name|title)).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vacancy (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dedup_hash            TEXT NOT NULL UNIQUE,
    company_id            UUID REFERENCES company(id) ON DELETE CASCADE,

    title                 TEXT NOT NULL,
    snippet               TEXT,
    full_description      TEXT,
    compensation          TEXT,
    deadline              DATE,
    department            TEXT,

    -- locations is an array of {work_mode, region, country, city, compensation, url}.
    -- A vacancy can be listed in several locations at once.
    locations             JSONB DEFAULT '[]',

    first_seen            DATE NOT NULL,
    last_seen             DATE NOT NULL,

    -- Triage decision. 'archived' is a status VALUE (not a column) — a vacancy
    -- removed from the active catalog (low score, gone from source, or manual).
    status                TEXT NOT NULL DEFAULT 'unseen'
                          CHECK (status IN ('unseen', 'liked', 'passed',
                                            'to_apply', 'to_research',
                                            'to_network', 'skipped', 'applied',
                                            'archived')),
    status_updated_at     TIMESTAMPTZ,

    -- LLM scoring output (filled by scripts/score_vacancies.py).
    llm_score             INTEGER,
    llm_reasoning         TEXT,
    llm_summary           TEXT,
    llm_tags              TEXT[] DEFAULT '{}',
    llm_hard_requirements JSONB DEFAULT '[]',
    llm_scored_at         TIMESTAMPTZ,
    us_eligibility        TEXT,  -- outside_us_ok|us_only|unclear (orthogonal to score)

    -- Free-form triage notes (filled by /triage flow).
    triage                JSONB DEFAULT '{}',

    -- Set by scripts/telegram_digest.py when a vacancy is pushed to the
    -- Telegram digest, so it is never sent twice.
    digest_sent_at        TIMESTAMPTZ,

    created_at            TIMESTAMPTZ DEFAULT NOW(),
    updated_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vacancy_company    ON vacancy (company_id);
CREATE INDEX IF NOT EXISTS idx_vacancy_status     ON vacancy (status);
CREATE INDEX IF NOT EXISTS idx_vacancy_dedup_hash ON vacancy (dedup_hash);
CREATE INDEX IF NOT EXISTS idx_vacancy_llm_score  ON vacancy (llm_score DESC NULLS LAST);

-- ---------------------------------------------------------------------------
-- archived_hash — tombstones for archived/removed vacancies.
-- When a vacancy is archived (low score, gone from source, junk), its
-- dedup_hash is recorded here so a lagging job board can't re-import the same
-- posting for a cooldown window. `reason` distinguishes a source-side close
-- ('gone_from_source') from other archival reasons — a direct ATS re-listing
-- can resurrect a 'gone_from_source' hash, lagging boards cannot.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS archived_hash (
    dedup_hash   TEXT PRIMARY KEY,
    reason       TEXT,
    archived_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_archived_hash_at ON archived_hash (archived_at);

-- ---------------------------------------------------------------------------
-- dashboard_snapshot — live-dashboard read source (full mode only).
-- One row holding the latest assembled VACANCY_DATA payload. generate_dashboard()
-- upserts it on every data change; /api/vacancies serves it so a browser refresh
-- shows current data with no redeploy. Simple/SQLite mode never reads this and
-- keeps using public/data.js, so the SQLite baseline omits this table.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dashboard_snapshot (
    id          TEXT PRIMARY KEY DEFAULT 'current',
    payload     JSONB NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Row-Level Security
--
-- Recommended setup if you serve the dashboard via Supabase anon key:
--   - anon: SELECT only
--   - service_role: full access (used by /api/* and Python scripts)
--
-- Uncomment the block below if you want RLS. By default this schema leaves
-- RLS disabled and assumes the dashboard reaches the DB through the Vercel
-- API endpoints (which use the service role key).
-- ---------------------------------------------------------------------------

-- ALTER TABLE company ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE vacancy ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY company_read_anon ON company FOR SELECT TO anon USING (true);
-- CREATE POLICY vacancy_read_anon ON vacancy FOR SELECT TO anon USING (true);
